language: node_js
node_js:
    - 9
install: npm install
jobs:
    include:
      - stage: test
        node_js: 9
        script: npm run lint
      - stage: build
        node_js: 9
        script: npm run build:gulp
