language: node_js
node_js:
    - 9
install: npm install
after_failure:
  - chmod +x ./travis/webhook.sh
  - ./travis/webhook.sh
jobs:
    include:
      - stage: test
        node_js: 9
        script: npm run lint
      - stage: build
        node_js: 9
        script: npm run build:gulp
      - stage: webhook
        script:
          - chmod +x ./travis/webhook.sh
          - ./travis/webhook.sh
