language: node_js
node_js:
    - 9
install: yarn
after_failure:
  - chmod +x ./travis/webhook.sh
  - ./travis/webhook.sh
jobs:
    include:
      - stage: test
        node_js: 9
        script: yarn lint
      - stage: build
        node_js: 9
        script: yarn build:gulp
      - stage: webhook
        script:
          - chmod +x ./travis/webhook.sh
          - ./travis/webhook.sh
