export type AnimeData = {
	adult: string;
	airing_status: string;
	average_score: number;
	description: string;
	duration: number;
	end_date_fuzzy: number;
	genres: string[];
	hashtag: string;
	id: number;
	image_url_banner: string;
	image_url_lge: string;
	image_url_med: string;
	image_url_sml: string;
	list_stats: {
		completed: number;
		on_hold: number;
		dropped: number;
		plan_to_watch: number;
		watching: number;
	};
	popularity: number;
	score_distribution: {
		10: number;
		20: number;
		30: number;
		40: number;
		50: number;
		60: number;
		70: number;
		80: number;
		90: number;
		100: number;
	};
	season: number;
	series_type: string;
	source: string;
	start_date_fuzzy: number;
	synonyms: string[];
	title_english: string;
	title_japanese: string;
	title_romaji: string;
	total_episodes: number;
	type: string;
	updated_at: number;
	youtube_id: string;
};
