export enum LocalizationStrings
{
	// decorators
	DECORATORS_MUSIC_ROLE_MEMBERS = 'DECORATORS_MUSIC_ROLE_MEMBERS',
	DECORATORS_MUSIC_TEXT_CHANNEL = 'DECORATORS_MUSIC_TEXT_CHANNEL',
	DECORATORS_MUSIC_VOICE_CHANNEL = 'DECORATORS_MUSIC_VOICE_CHANNEL',
	DECORATORS_REPORT_ERROR_TEXT = 'DECORATORS_REPORT_ERROR_TEXT',

	// config
	CMD_CONFIGOVERVIEW_EXPLANATION = 'CMD_CONFIGOVERVIEW_EXPLANATION',
	CMD_CONFIG_KEY_NOT_SET_UP = 'CMD_CONFIG_KEY_NOT_SET_UP',
	CMD_CONFIG_NOT_PRESENT = 'CMD_CONFIG_NOT_PRESENT',
	CMD_CONFIG_CURRENT_VALUE = 'CMD_CONFIG_CURRENT_VALUE',
	CMD_CONFIG_VALUE_MUST_BE_TEXTCHANNEL = 'CMD_CONFIG_VALUE_MUST_BE_TEXTCHANNEL',
	CMD_CONFIG_VALUE_UPDATE = 'CMD_CONFIG_VALUE_UPDATE',
	CMD_CONFIG_RESET_PROMPT = 'CMD_CONFIG_RESET_PROMPT',
	CMD_CONFIG_RESET_ABORT = 'CMD_CONFIG_RESET_ABORT',
	CMD_CONFIG_RESET_SUCCESS = 'CMD_CONFIG_RESET_SUCCESS',

	// moderation
	CMD_PRUNE_INVALID_COUNT = 'CMD_PRUNE_INVALID_COUNT',

	// picture
	CMD_DONMAI_TOO_MUCH_TAGS = 'CMD_DONMAI_TOO_MUCH_TAGS',
	CMD_KONACHAN_TOO_MUCH_TAGS = 'CMD_KONACHAN_TOO_MUCH_TAGS',

	// misc
	CMD_EMOJI_COULD_NOT_RESOLVE_EMOJI = 'CMD_EMOJI_COULD_NOT_RESOLVE_EMOJI',
	CMD_EMOJI_COULD_NOT_RESOLVE_MESSAGE = 'CMD_EMOJI_COULD_NOT_RESOLVE_MESSAGE',

	CMD_URBAN_DEFINITION = 'CMD_URBAN_DEFINITION',
	CMD_URBAN_EXAMPLE = 'CMD_URBAN_EXAMPLE',
	CMD_URBAN_FOOTER = 'CMD_URBAN_FOOTER',

	// info
	CMD_GUILDINFO_RESOLVE_FAILED = 'CMD_GUILDINFO_RESOLVE_FAILED',
	CMD_GUILDINFO_EMBED_TITLE = 'CMD_GUILDINFO_EMBED_TITLE',
	CMD_GUILDINFO_EMBED_BOTH_MEMBERS_TITLE = 'CMD_GUILDINFO_EMBED_BOTH_MEMBERS_TITLE',
	CMD_GUILDINFO_EMBED_BOTH_CREATED_TITLE = 'CMD_GUILDINFO_EMBED_BOTH_CREATED_TITLE',
	CMD_GUILDINFO_EMBED_BOTH_CREATED_VALUE = 'CMD_GUILDINFO_EMBED_BOTH_CREATED_VALUE',
	CMD_GUILDINFO_EMBED_FULL_CHANNELS_TITLE = 'CMD_GUILDINFO_EMBED_FULL_CHANNELS_TITLE',
	CMD_GUILDINFO_EMBED_FULL_CHANNELS_VALUE = 'CMD_GUILDINFO_EMBED_FULL_CHANNELS_VALUE',
	CMD_GUILDINFO_EMBED_FULL_MEMBERS_VALUE = 'CMD_GUILDINFO_EMBED_FULL_MEMBERS_VALUE',
	CMD_GUILDINFO_EMBED_FULL_REGION_TITLE = 'CMD_GUILDINFO_EMBED_FULL_REGION_TITLE',
	CMD_GUILDINFO_EMBED_FULL_ROLES_TITLE = 'CMD_GUILDINFO_EMBED_FULL_ROLES_TITLE',
	CMD_GUILDINFO_EMBED_FULL_ROLES_VALUE = 'CMD_GUILDINFO_EMBED_FULL_ROLES_VALUE',
	CMD_GUILDINFO_EMBED_FULL_EMOJI_TITLE = 'CMD_GUILDINFO_EMBED_FULL_EMOJI_TITLE',
	CMD_GUILDINFO_EMBED_PARTIAL_DESCRIPTION = 'CMD_GUILDINFO_EMBED_PARTIAL_DESCRIPTION',
	CMD_GUILDINFO_EMBED_PARTIAL_CHANNEL_TITLE = 'CMD_GUILDINFO_EMBED_PARTIAL_CHANNEL_TITLE',
	CMD_GUILDINFO_EMBED_PARTIAL_CHANNEL_VALUE = 'CMD_GUILDINFO_EMBED_PARTIAL_CHANNEL_VALUE',
	CMD_GUILDINFO_EMBED_PARTIAL_MEMBERS_VALUE = 'CMD_GUILDINFO_EMBED_PARTIAL_MEMBERS_VALUE',

	CMD_INFO_TITLE = 'CMD_INFO_TITLE',
	CMD_INFO_UPTIME_TITLE = 'CMD_INFO_UPTIME_TITLE',
	CMD_INFO_UPTIME_FORMAT_STRING = 'CMD_INFO_UPTIME_FORMAT_STRING',
	CMD_INFO_VERSIONS = 'CMD_INFO_VERSIONS',
	CMD_INFO_UPTIME_MEMORY_USAGE_TITLE = 'CMD_INFO_UPTIME_MEMORY_USAGE_TITLE',
	CMD_INFO_OWNER_TITLE = 'CMD_INFO_OWNER_TITLE',
	CMD_INFO_VOICE_CONNECTIONS_TITLE = 'CMD_INFO_VOICE_CONNECTIONS_TITLE',
	CMD_INFO_RECENT_CHANGES = 'CMD_INFO_RECENT_CHANGES',

	CMD_USERINFO_MOMENT_FORMAT = 'CMD_USERINFO_MOMENT_FORMAT',
	CMD_USERINFO_CREATE_OR_JOIN_FORMAT = 'CMD_USERINFO_CREATE_OR_JOIN_FORMAT',
	CMD_USERINFO_GAMESTATUS = 'CMD_USERINFO_GAMESTATUS',
	CMD_USERINFO_GLOBAL_TITLE = 'CMD_USERINFO_GLOBAL_TITLE',
	CMD_USERINFO_GLOBAL_VALUE = 'CMD_USERINFO_GLOBAL_VALUE',
	CMD_USERINFO_MEMBER_TITLE = 'CMD_USERINFO_MEMBER_TITLE',
	CMD_USERINFO_MEMBER_VALUE = 'CMD_USERINFO_MEMBER_VALUE',
	CMD_USERINFO_N_A = 'CMD_USERINFO_N_A',
	CMD_USERINFO_AVATAR = 'CMD_USERINFO_AVATAR',

	// util
	CMD_INIVTE_EMBED_AUTHOR = 'CMD_INIVTE_EMBED_AUTHOR',
	CMD_INVITE_EMBED_DESCRIPTION = 'CMD_INVITE_EMBED_DESCRIPTION',
	CMD_INVITE_EMBED_FIELD_TITLE = 'CMD_INVITE_EMBED_FIELD_TITLE',
	CMD_INVITE_EMBED_FIELD_VALUE = 'CMD_INVITE_EMBED_FIELD_VALUE',

	CMD_WHITELIST_DEPRECATED = 'CMD_WHITELIST_DEPRECATED',

	// music
	CMD_LOOP_CURRENT_STATE = 'CMD_LOOP_CURRENT_STATE',
	CMD_LOOP_CURRENT_ALREADY = 'CMD_LOOP_CURRENT_ALREADY',
	CMD_LOOP_CURRENT_SET = 'CMD_LOOP_CURRENT_SET',

	CMD_PAUSE_ALREADY_PAUSED = 'CMD_PAUSE_ALREADY_PAUSED',
	CMD_PAUSE_SUCCESS = 'CMD_PAUSE_SUCCESS',

	CMD_PLAY_DIFFERENT_CHANNEL = 'CMD_PLAY_DIFFERENT_CHANNEL',
	CMD_PLAY_FETCHING_MESSAGE = 'CMD_PLAY_FETCHING_MESSAGE',
	CMD_PLAY_NOTHING_FOUND = 'CMD_PLAY_NOTHING_FOUND',
	CMD_PLAY_NOTHING_QUALIFIED = 'CMD_PLAY_NOTHING_QUALIFIED',
	CMD_PLAY_VALIDATE_FOOTER = 'CMD_PLAY_VALIDATE_FOOTER',
	CMD_PLAY_VALIDATE_DESCRIPTION = 'CMD_PLAY_VALIDATE_DESCRIPTION',
	CMD_PLAY_VALIDATE_ALREADY_QUEUED = 'CMD_PLAY_VALIDATE_ALREADY_QUEUED',
	CMD_PLAY_VALIDATE_TOO_LONG = 'CMD_PLAY_VALIDATE_TOO_LONG',
	CMD_PLAY_PICK_DESCRIPTION = 'CMD_PLAY_PICK_DESCRIPTION',
	CMD_PLAY_PICK_FOOTER = 'CMD_PLAY_PICK_FOOTER',

	CMD_QUEUE_EMBED_TITLE = 'CMD_QUEUE_EMBED_TITLE',
	CMD_QUEUE_EMBED_FOOTER = 'CMD_QUEUE_EMBED_FOOTER',
	CMD_QUEUE_LOOP_ENABLED = 'CMD_QUEUE_LOOP_ENABLED',
	CMD_QUEUE_CUURENTLY_PLAYING = 'CMD_QUEUE_CUURENTLY_PLAYING',
	CMD_QUEUE_CURRENTLY_PAUSED = 'CMD_QUEUE_CURRENTLY_PAUSED',
	CMD_QUEUE_CURRENT_TIME = 'CMD_QUEUE_CURRENT_TIME',
	CMD_QUEUE_QUEUE = 'CMD_QUEUE_QUEUE',

	CMD_REMOVE_NOT_FOUND = 'CMD_REMOVE_NOT_FOUND',
	CMD_REMOVE_SUCCESS = 'CMD_REMOVE_SUCCESS',

	CMD_RESUME_ALREADY_RUNNING = 'CMD_RESUME_ALREADY_RUNNING',
	CMD_RESUME_SUCCESS = 'CMD_RESUME_SUCCESS',

	CMD_SAVE_DM_FAILED = 'CMD_SAVE_DM_FAILED',

	CMD_SHUFFLE_QUEUE_EMPTY_OR_TOO_SMALL = 'CMD_SHUFFLE_QUEUE_EMPTY_OR_TOO_SMALL',
	CMD_SHUFFLE_SUCCESS = 'CMD_SHUFFLE_SUCCESS',

	CMD_SKIP_NOT_POSSIBLE_YET = 'CMD_SKIP_NOT_POSSIBLE_YET',
	CMD_SKIP_SUCCESS = 'CMD_SKIP_SUCCESS',

	CMD_STOP_NOT_YET_POSSIBLE = 'CMD_STOP_NOT_YET_POSSIBLE',
	CMD_STOP_SUCCESS = 'CMD_STOP_SUCCESS',

	CMD_SUMMON_JOINING = 'CMD_SUMMON_JOINING',
	CMD_SUMMON_JOINED = 'CMD_SUMMON_JOINED',

	CMD_VOLUME_TOO_HIGH = 'CMD_VOLUME_TOO_HIGH',
	CMD_VOLUME_TOO_LOW = 'CMD_VOLUME_TOO_LOW',
	CMD_VOLUME_SUCCESS = 'CMD_VOLUME_SUCCESS',

	MUSIC_LIVESTREAM = 'MUSIC_LIVESTREAM',
	MUSIC_QUEUE_NON_EXISTENT = 'MUSIC_QUEUE_NON_EXISTENT',
	MUSIC_EMPTY_TIMEOUT = 'MUSIC_EMPTY_TIMEOUT',
	MUSIC_NOT_IN_VOICECHANNEL = 'MUSIC_NOT_IN_VOICECHANNEL',
	MUSIC_NO_SPEAK = 'MUSIC_NO_SPEAK',
	MUSIC_NO_CONNECT = 'MUSIC_NO_CONNECT',
	MUSIC_NO_DISPATCHER = 'MUSIC_NO_DISPATCHER',
	MUSIC_JOIN_FAILED = 'MUSIC_JOIN_FAILED',
	MUSIC_YOUTUBE_ERROR = 'MUSIC_YOUTUBE_ERROR',
	MUSIC_PLAY_ERROR = 'MUSIC_PLAY_ERROR',
	MUSIC_SONG_LOOP = 'MUSIC_SONG_LOOP',
	MUSIC_SONG_NP_DESCRIPTION = 'MUSIC_SONG_NP_DESCRIPTION',
	MUSIC_SONGS_GENERIC_DESCRIPTION = 'MUSIC_SONGS_GENERIC_DESCRIPTION',
	MUSIC_EMBED_FOOTER_ADDED = 'MUSIC_EMBED_FOOTER_ADDED',
	MUSIC_EMBED_FOOTER_PLAYING = 'MUSIC_EMBED_FOOTER_PLAYING',
	MUSIC_EMBED_FOOTER_SAVED = 'MUSIC_EMBED_FOOTER_SAVED',
	MUSIC_EMBED_FOOTER_NP = 'MUSIC_EMBED_FOOTER_NP',

	// generic
	CMD_NO_RESULTS_TITLE = 'CMD_NO_RESULTS_TITLE',
	CMD_NO_RESULTS_VALUE = 'CMD_NO_RESULTS_VALUE',
	CMD_NO_RESULTS_SEARCH = 'CMD_NO_RESULTS_SEARCH',
	CMD_NO_RESULTS_URL = 'CMD_NO_RESULTS_URL',
	CMD_RESULTS_SOURCE = 'CMD_RESULTS_SOURCE',
	CMD_ABORTING = 'CMD_ABORTING',
	UTIL_RESOLVE_BOOLEAN = 'UTIL_RESOLVE_BOOLEAN',

	// events
	EVENT_VOICELOG_DISCONNECT = 'EVENT_VOICELOG_DISCONNECT',
	EVENT_VOICELOG_CONNECT = 'EVENT_VOICELOG_CONNECT',
	EVENT_VOICELOG_MOVE = 'EVENT_VOICELOG_MOVE',

	// base strings
	EXPECT_ERR_INVALID_OPTION = 'EXPECT_ERR_INVALID_OPTION',
}
